In [1]:
%%time
import tensorflow as tf
import numpy as np
print(tf.__version__)

C:\Users\metya\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


1.9.0
Wall time: 3.18 s


In [2]:
tf.Graph()

In [3]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
print(sess.run({'ab':(a, b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [48]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))
print(sess.run(vec))

[0.6904112 0.8159572 0.5298717]
[0.4325726  0.9066334  0.14541471]
(array([1.2638401, 1.0028721, 1.4967339], dtype=float32), array([2.2638402, 2.002872 , 2.496734 ], dtype=float32))
[0.05967903 0.7202333  0.01634872]


In [8]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [9]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [10]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [11]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[-0.03551756  0.86909735  0.29059976]
[-0.5752694  -0.04043542 -0.14040105]
[-1.8306396  0.5925847  0.8758052]
[ 0.4816003  -2.5911448   0.61039466]
[0.22580892 1.659448   1.1092222 ]
[-0.8010745 -0.6309554 -1.1165694]
[-0.04138372  1.2136327   0.13442184]
[-1.6996489  -0.44398734 -1.3547816 ]
[-0.99797904  0.12640646 -0.12847602]
[ 0.9065686  -0.65298986  0.22719783]


In [50]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [13]:
init = tf.global_variables_initializer()
sess.run(init)

In [14]:
print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[-1.9988847]
 [-7.050103 ]]


In [15]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.layers.dense(x, units=1)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[-3.0810857]
 [-8.495519 ]]


In [51]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [17]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [18]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


In [19]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [20]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)

In [21]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[-1.1782258]
 [-2.3564515]
 [-3.5346773]
 [-4.712903 ]]


In [22]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

print(sess.run(loss))

2.129362


In [23]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [53]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

0.062355645
0.06198283
0.06161224
0.061243888
0.060877703
0.06051374
0.060151923
0.059792273
0.059434794
0.059079442
0.05872623
0.058375098
0.058026087
0.05767916
0.05733429
0.05699151
0.056650754
0.056312058
0.055975392
0.055640712
0.055308033
0.05497738
0.054648668
0.05432192
0.05399715
0.05367431
0.053353406
0.053034402
0.05271734
0.052402154
0.052088827
0.051777393
0.051467825
0.051160105
0.050854225
0.0505502
0.050247956
0.04994753
0.0496489
0.049352057
0.04905699
0.048763696
0.048472136
0.04818233
0.047894254
0.04760789
0.04732326
0.04704031
0.046759084
0.04647951
0.046201624
0.04592538
0.045650806
0.045377854
0.045106556
0.04483687
0.044568792
0.04430233
0.044037465
0.043774165
0.043512456
0.04325229
0.042993702
0.042736642
0.042481128
0.042227138
0.04197466
0.041723717
0.041474245
0.041226275
0.040979788
0.040734764
0.040491223
0.04024914
0.040008504
0.039769303
0.039531514
0.039295174
0.03906024
0.038826685
0.038594555
0.038363796
0.03813443
0.03790642
0.037679795
0.037454523


In [28]:
p = tf.placeholder(tf.float32)
t = p + 1.0
# t.eval(session=sess)  # This will fail, since the placeholder did not get a value.
t.eval(feed_dict={p:2.0})  # This will succeed because we're feeding a value
                           # to the placeholder.

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [29]:
my_variable = tf.get_variable("my_variable", [1, 2, 3])

In [30]:
my_int_variable = tf.get_variable("my_int_variable", [1, 2, 3], dtype=tf.int32,
  initializer=tf.zeros_initializer)

In [31]:
other_variable = tf.get_variable("other_variable", dtype=tf.int32,
  initializer=tf.constant([23, 42]))

In [32]:
my_local = tf.get_variable("my_local", shape=(),
collections=[tf.GraphKeys.LOCAL_VARIABLES])

In [33]:
my_non_trainable = tf.get_variable("my_non_trainable",
                                   shape=(),
                                   trainable=False)

In [34]:
tf.add_to_collection("my_collection_name", my_local)

In [35]:
tf.get_collection("my_collection_name")

[<tf.Variable 'my_local:0' shape=() dtype=float32_ref>]

In [39]:
sess.run(tf.global_variables_initializer())
# Now all variables are initialized.
sess.run(my_variable.initializer)

In [40]:
print(sess.run(tf.report_uninitialized_variables()))

[b'my_local']


In [47]:
v = tf.get_variable("v", shape=(), initializer=tf.zeros_initializer())
assignment = v.assign_add(1)
tf.global_variables_initializer().run()

ValueError: Variable v already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Users\metya\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
  File "C:\Users\metya\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\metya\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)


SyntaxError: unexpected EOF while parsing (<ipython-input-54-2846b56d51dd>, line 1)

In [55]:
with Session(file) as f:
    read(f)

SyntaxError: unexpected EOF while parsing (<ipython-input-55-80a3ebe066ac>, line 1)